//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.11 at 08:23:43 PM CEST 
//


package com.rhizomind.ds.integrations.owasp;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigDecimal;


/**
 * <p>Java class for cvssV2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cvssV2"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="accessVector" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="accessComplexity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="authenticationr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="confidentialImpact" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="integrityImpact" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="availabilityImpact" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="severity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="exploitabilityScore" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="impactScore" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="acInsufInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="obtainAllPrivilege" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="obtainUserPrivilege" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="obtainOtherPrivilege" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="userInteractionRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cvssV2", propOrder = {
    "score",
    "accessVector",
    "accessComplexity",
    "authenticationr",
    "confidentialImpact",
    "integrityImpact",
    "availabilityImpact",
    "severity",
    "version",
    "exploitabilityScore",
    "impactScore",
    "acInsufInfo",
    "obtainAllPrivilege",
    "obtainUserPrivilege",
    "obtainOtherPrivilege",
    "userInteractionRequired"
})
public class CvssV2 {

    @XmlElement(required = true)
    protected BigDecimal score;
    @XmlElement(required = true)
    protected String accessVector;
    @XmlElement(required = true)
    protected String accessComplexity;
    @XmlElement(required = true)
    protected String authenticationr;
    @XmlElement(required = true)
    protected String confidentialImpact;
    @XmlElement(required = true)
    protected String integrityImpact;
    @XmlElement(required = true)
    protected String availabilityImpact;
    @XmlElement(required = true)
    protected String severity;
    protected BigDecimal version;
    protected BigDecimal exploitabilityScore;
    protected BigDecimal impactScore;
    protected Boolean acInsufInfo;
    protected Boolean obtainAllPrivilege;
    protected Boolean obtainUserPrivilege;
    protected Boolean obtainOtherPrivilege;
    protected Boolean userInteractionRequired;

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setScore(BigDecimal value) {
        this.score = value;
    }

    /**
     * Gets the value of the accessVector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessVector() {
        return accessVector;
    }

    /**
     * Sets the value of the accessVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessVector(String value) {
        this.accessVector = value;
    }

    /**
     * Gets the value of the accessComplexity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessComplexity() {
        return accessComplexity;
    }

    /**
     * Sets the value of the accessComplexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessComplexity(String value) {
        this.accessComplexity = value;
    }

    /**
     * Gets the value of the authenticationr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthenticationr() {
        return authenticationr;
    }

    /**
     * Sets the value of the authenticationr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthenticationr(String value) {
        this.authenticationr = value;
    }

    /**
     * Gets the value of the confidentialImpact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidentialImpact() {
        return confidentialImpact;
    }

    /**
     * Sets the value of the confidentialImpact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidentialImpact(String value) {
        this.confidentialImpact = value;
    }

    /**
     * Gets the value of the integrityImpact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegrityImpact() {
        return integrityImpact;
    }

    /**
     * Sets the value of the integrityImpact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegrityImpact(String value) {
        this.integrityImpact = value;
    }

    /**
     * Gets the value of the availabilityImpact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityImpact() {
        return availabilityImpact;
    }

    /**
     * Sets the value of the availabilityImpact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityImpact(String value) {
        this.availabilityImpact = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverity(String value) {
        this.severity = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the exploitabilityScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExploitabilityScore() {
        return exploitabilityScore;
    }

    /**
     * Sets the value of the exploitabilityScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExploitabilityScore(BigDecimal value) {
        this.exploitabilityScore = value;
    }

    /**
     * Gets the value of the impactScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImpactScore() {
        return impactScore;
    }

    /**
     * Sets the value of the impactScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImpactScore(BigDecimal value) {
        this.impactScore = value;
    }

    /**
     * Gets the value of the acInsufInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcInsufInfo() {
        return acInsufInfo;
    }

    /**
     * Sets the value of the acInsufInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcInsufInfo(Boolean value) {
        this.acInsufInfo = value;
    }

    /**
     * Gets the value of the obtainAllPrivilege property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isObtainAllPrivilege() {
        return obtainAllPrivilege;
    }

    /**
     * Sets the value of the obtainAllPrivilege property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setObtainAllPrivilege(Boolean value) {
        this.obtainAllPrivilege = value;
    }

    /**
     * Gets the value of the obtainUserPrivilege property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isObtainUserPrivilege() {
        return obtainUserPrivilege;
    }

    /**
     * Sets the value of the obtainUserPrivilege property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setObtainUserPrivilege(Boolean value) {
        this.obtainUserPrivilege = value;
    }

    /**
     * Gets the value of the obtainOtherPrivilege property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isObtainOtherPrivilege() {
        return obtainOtherPrivilege;
    }

    /**
     * Sets the value of the obtainOtherPrivilege property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setObtainOtherPrivilege(Boolean value) {
        this.obtainOtherPrivilege = value;
    }

    /**
     * Gets the value of the userInteractionRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserInteractionRequired() {
        return userInteractionRequired;
    }

    /**
     * Sets the value of the userInteractionRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserInteractionRequired(Boolean value) {
        this.userInteractionRequired = value;
    }

}
