//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.11 at 08:23:43 PM CEST 
//


package com.rhizomind.ds.integrations.owasp;

import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for dependency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dependency"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filePath" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="md5" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sha1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sha256" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="license" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="projectReferences" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="projectReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="relatedDependencies" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="relatedDependency" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}relatedDependency"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="evidenceCollected" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="evidence" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}evidence"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="identifiers" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;element name="package" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}identifier"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;element name="vulnerabilityIds" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}identifier"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;element name="suppressedVulnerabilityIds" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}identifier"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="vulnerabilities" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;element name="vulnerability" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}vulnerability"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;element name="suppressedVulnerability" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}vulnerability"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isVirtual" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dependency", propOrder = {
    "fileName",
    "filePath",
    "md5",
    "sha1",
    "sha256",
    "description",
    "license",
    "projectReferences",
    "relatedDependencies",
    "evidenceCollected",
    "identifiers",
    "vulnerabilities"
})
public class Dependency {

    @XmlElement(required = true)
    protected String fileName;
    @XmlElement(required = true)
    protected String filePath;
    @XmlElement(required = true)
    protected String md5;
    @XmlElement(required = true)
    protected String sha1;
    @XmlElement(required = true)
    protected String sha256;
    protected String description;
    protected String license;
    protected ProjectReferences projectReferences;
    protected RelatedDependencies relatedDependencies;
    protected EvidenceCollected evidenceCollected;
    protected Identifiers identifiers;
    protected Vulnerabilities vulnerabilities;
    @XmlAttribute(name = "isVirtual", required = true)
    protected boolean isVirtual;

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the filePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * Sets the value of the filePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilePath(String value) {
        this.filePath = value;
    }

    /**
     * Gets the value of the md5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMd5() {
        return md5;
    }

    /**
     * Sets the value of the md5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMd5(String value) {
        this.md5 = value;
    }

    /**
     * Gets the value of the sha1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSha1() {
        return sha1;
    }

    /**
     * Sets the value of the sha1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSha1(String value) {
        this.sha1 = value;
    }

    /**
     * Gets the value of the sha256 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSha256() {
        return sha256;
    }

    /**
     * Sets the value of the sha256 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSha256(String value) {
        this.sha256 = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicense(String value) {
        this.license = value;
    }

    /**
     * Gets the value of the projectReferences property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectReferences }
     *     
     */
    public ProjectReferences getProjectReferences() {
        return projectReferences;
    }

    /**
     * Sets the value of the projectReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectReferences }
     *     
     */
    public void setProjectReferences(ProjectReferences value) {
        this.projectReferences = value;
    }

    /**
     * Gets the value of the relatedDependencies property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedDependencies }
     *     
     */
    public RelatedDependencies getRelatedDependencies() {
        return relatedDependencies;
    }

    /**
     * Sets the value of the relatedDependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedDependencies }
     *     
     */
    public void setRelatedDependencies(RelatedDependencies value) {
        this.relatedDependencies = value;
    }

    /**
     * Gets the value of the evidenceCollected property.
     * 
     * @return
     *     possible object is
     *     {@link EvidenceCollected }
     *     
     */
    public EvidenceCollected getEvidenceCollected() {
        return evidenceCollected;
    }

    /**
     * Sets the value of the evidenceCollected property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvidenceCollected }
     *     
     */
    public void setEvidenceCollected(EvidenceCollected value) {
        this.evidenceCollected = value;
    }

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link Identifiers }
     *     
     */
    public Identifiers getIdentifiers() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifiers }
     *     
     */
    public void setIdentifiers(Identifiers value) {
        this.identifiers = value;
    }

    /**
     * Gets the value of the vulnerabilities property.
     * 
     * @return
     *     possible object is
     *     {@link Vulnerabilities }
     *     
     */
    public Vulnerabilities getVulnerabilities() {
        return vulnerabilities;
    }

    /**
     * Sets the value of the vulnerabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vulnerabilities }
     *     
     */
    public void setVulnerabilities(Vulnerabilities value) {
        this.vulnerabilities = value;
    }

    /**
     * Gets the value of the isVirtual property.
     * 
     */
    public boolean isIsVirtual() {
        return isVirtual;
    }

    /**
     * Sets the value of the isVirtual property.
     * 
     */
    public void setIsVirtual(boolean value) {
        this.isVirtual = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="evidence" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}evidence"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "evidence"
    })
    public static class EvidenceCollected {

        protected List<Evidence> evidence;

        /**
         * Gets the value of the evidence property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the evidence property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvidence().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Evidence }
         * 
         * 
         */
        public List<Evidence> getEvidence() {
            if (evidence == null) {
                evidence = new ArrayList<Evidence>();
            }
            return this.evidence;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;element name="package" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}identifier"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;element name="vulnerabilityIds" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}identifier"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;element name="suppressedVulnerabilityIds" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}identifier"/&gt;
     *         &lt;/sequence&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_package",
        "vulnerabilityIds",
        "suppressedVulnerabilityIds"
    })
    public static class Identifiers {

        @XmlElement(name = "package")
        protected List<Identifier> _package;
        protected List<Identifier> vulnerabilityIds;
        protected List<Identifier> suppressedVulnerabilityIds;

        /**
         * Gets the value of the package property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the package property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPackage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Identifier }
         * 
         * 
         */
        public List<Identifier> getPackage() {
            if (_package == null) {
                _package = new ArrayList<Identifier>();
            }
            return this._package;
        }

        /**
         * Gets the value of the vulnerabilityIds property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the vulnerabilityIds property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVulnerabilityIds().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Identifier }
         * 
         * 
         */
        public List<Identifier> getVulnerabilityIds() {
            if (vulnerabilityIds == null) {
                vulnerabilityIds = new ArrayList<Identifier>();
            }
            return this.vulnerabilityIds;
        }

        /**
         * Gets the value of the suppressedVulnerabilityIds property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the suppressedVulnerabilityIds property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSuppressedVulnerabilityIds().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Identifier }
         * 
         * 
         */
        public List<Identifier> getSuppressedVulnerabilityIds() {
            if (suppressedVulnerabilityIds == null) {
                suppressedVulnerabilityIds = new ArrayList<Identifier>();
            }
            return this.suppressedVulnerabilityIds;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="projectReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "projectReference"
    })
    public static class ProjectReferences {

        protected List<String> projectReference;

        /**
         * Gets the value of the projectReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the projectReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProjectReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getProjectReference() {
            if (projectReference == null) {
                projectReference = new ArrayList<String>();
            }
            return this.projectReference;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="relatedDependency" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}relatedDependency"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relatedDependency"
    })
    public static class RelatedDependencies {

        protected List<RelatedDependency> relatedDependency;

        /**
         * Gets the value of the relatedDependency property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the relatedDependency property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelatedDependency().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RelatedDependency }
         * 
         * 
         */
        public List<RelatedDependency> getRelatedDependency() {
            if (relatedDependency == null) {
                relatedDependency = new ArrayList<RelatedDependency>();
            }
            return this.relatedDependency;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;element name="vulnerability" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}vulnerability"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;element name="suppressedVulnerability" type="{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}vulnerability"/&gt;
     *         &lt;/sequence&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vulnerability",
        "suppressedVulnerability"
    })
    public static class Vulnerabilities {

        protected List<Vulnerability> vulnerability;
        protected List<Vulnerability> suppressedVulnerability;

        /**
         * Gets the value of the vulnerability property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the vulnerability property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVulnerability().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Vulnerability }
         * 
         * 
         */
        public List<Vulnerability> getVulnerability() {
            if (vulnerability == null) {
                vulnerability = new ArrayList<Vulnerability>();
            }
            return this.vulnerability;
        }

        /**
         * Gets the value of the suppressedVulnerability property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the suppressedVulnerability property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSuppressedVulnerability().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Vulnerability }
         * 
         * 
         */
        public List<Vulnerability> getSuppressedVulnerability() {
            if (suppressedVulnerability == null) {
                suppressedVulnerability = new ArrayList<Vulnerability>();
            }
            return this.suppressedVulnerability;
        }

    }

}
