//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.11 at 08:23:43 PM CEST 
//


package com.rhizomind.ds.integrations.owasp;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for software complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="software"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="vulnerabilityIdMatched" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="versionStartIncluding" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="versionStartExcluding" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="versionEndIncluding" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="versionEndExcluding" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="vulnerable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "software", propOrder = {
    "value"
})
public class Software {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "vulnerabilityIdMatched")
    protected Boolean vulnerabilityIdMatched;
    @XmlAttribute(name = "versionStartIncluding")
    protected String versionStartIncluding;
    @XmlAttribute(name = "versionStartExcluding")
    protected String versionStartExcluding;
    @XmlAttribute(name = "versionEndIncluding")
    protected String versionEndIncluding;
    @XmlAttribute(name = "versionEndExcluding")
    protected String versionEndExcluding;
    @XmlAttribute(name = "vulnerable")
    protected Boolean vulnerable;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the vulnerabilityIdMatched property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVulnerabilityIdMatched() {
        return vulnerabilityIdMatched;
    }

    /**
     * Sets the value of the vulnerabilityIdMatched property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVulnerabilityIdMatched(Boolean value) {
        this.vulnerabilityIdMatched = value;
    }

    /**
     * Gets the value of the versionStartIncluding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionStartIncluding() {
        return versionStartIncluding;
    }

    /**
     * Sets the value of the versionStartIncluding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionStartIncluding(String value) {
        this.versionStartIncluding = value;
    }

    /**
     * Gets the value of the versionStartExcluding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionStartExcluding() {
        return versionStartExcluding;
    }

    /**
     * Sets the value of the versionStartExcluding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionStartExcluding(String value) {
        this.versionStartExcluding = value;
    }

    /**
     * Gets the value of the versionEndIncluding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionEndIncluding() {
        return versionEndIncluding;
    }

    /**
     * Sets the value of the versionEndIncluding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionEndIncluding(String value) {
        this.versionEndIncluding = value;
    }

    /**
     * Gets the value of the versionEndExcluding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionEndExcluding() {
        return versionEndExcluding;
    }

    /**
     * Sets the value of the versionEndExcluding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionEndExcluding(String value) {
        this.versionEndExcluding = value;
    }

    /**
     * Gets the value of the vulnerable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVulnerable() {
        return vulnerable;
    }

    /**
     * Sets the value of the vulnerable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVulnerable(Boolean value) {
        this.vulnerable = value;
    }

}
