//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 10:22:52 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://maven.apache.org/POM/4.0.0", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.rhizomind.ds.integrations.maven.project.v400;
