//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.11 at 08:23:43 PM CEST 
//


package com.rhizomind.ds.integrations.owasp.v25;

import com.rhizomind.ds.integrations.owasp.Analysis;
import com.rhizomind.ds.integrations.owasp.CvssV2;
import com.rhizomind.ds.integrations.owasp.CvssV3;
import com.rhizomind.ds.integrations.owasp.Dependency;
import com.rhizomind.ds.integrations.owasp.Evidence;
import com.rhizomind.ds.integrations.owasp.Exception;
import com.rhizomind.ds.integrations.owasp.Identifier;
import com.rhizomind.ds.integrations.owasp.ProjectInfo;
import com.rhizomind.ds.integrations.owasp.Reference;
import com.rhizomind.ds.integrations.owasp.RelatedDependency;
import com.rhizomind.ds.integrations.owasp.ScanInfo;
import com.rhizomind.ds.integrations.owasp.Severity;
import com.rhizomind.ds.integrations.owasp.Software;
import com.rhizomind.ds.integrations.owasp.Vulnerability;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rhizomind.ds.integrations.owasp.v25 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rhizomind.ds.integrations.owasp.v25
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Analysis }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Analysis createAnalysis() {
        return new com.rhizomind.ds.integrations.owasp.Analysis();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Dependency }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Dependency createDependency() {
        return new com.rhizomind.ds.integrations.owasp.Dependency();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Vulnerability }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Vulnerability createVulnerability() {
        return new com.rhizomind.ds.integrations.owasp.Vulnerability();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.RelatedDependency }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.RelatedDependency createRelatedDependency() {
        return new com.rhizomind.ds.integrations.owasp.RelatedDependency();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Exception }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Exception createException() {
        return new com.rhizomind.ds.integrations.owasp.Exception();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.ScanInfo }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.ScanInfo createScanInfo() {
        return new com.rhizomind.ds.integrations.owasp.ScanInfo();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.ProjectInfo }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.ProjectInfo createProjectInfo() {
        return new ProjectInfo();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Analysis.Dependencies }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Analysis.Dependencies createAnalysisDependencies() {
        return new Analysis.Dependencies();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Identifier }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Evidence }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Evidence createEvidence() {
        return new Evidence();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.CvssV2 }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.CvssV2 createCvssV2() {
        return new CvssV2();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.CvssV3 }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.CvssV3 createCvssV3() {
        return new CvssV3();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Reference }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Software }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Software createSoftware() {
        return new Software();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Severity }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Severity createSeverity() {
        return new Severity();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Dependency.ProjectReferences }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Dependency.ProjectReferences createDependencyProjectReferences() {
        return new com.rhizomind.ds.integrations.owasp.Dependency.ProjectReferences();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Dependency.RelatedDependencies }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Dependency.RelatedDependencies createDependencyRelatedDependencies() {
        return new com.rhizomind.ds.integrations.owasp.Dependency.RelatedDependencies();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Dependency.EvidenceCollected }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Dependency.EvidenceCollected createDependencyEvidenceCollected() {
        return new com.rhizomind.ds.integrations.owasp.Dependency.EvidenceCollected();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Dependency.Identifiers }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Dependency.Identifiers createDependencyIdentifiers() {
        return new com.rhizomind.ds.integrations.owasp.Dependency.Identifiers();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Dependency.Vulnerabilities }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Dependency.Vulnerabilities createDependencyVulnerabilities() {
        return new Dependency.Vulnerabilities();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Vulnerability.Cwes }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Vulnerability.Cwes createVulnerabilityCwes() {
        return new com.rhizomind.ds.integrations.owasp.Vulnerability.Cwes();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Vulnerability.References }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Vulnerability.References createVulnerabilityReferences() {
        return new com.rhizomind.ds.integrations.owasp.Vulnerability.References();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Vulnerability.VulnerableSoftware }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Vulnerability.VulnerableSoftware createVulnerabilityVulnerableSoftware() {
        return new Vulnerability.VulnerableSoftware();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.RelatedDependency.Identifiers }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.RelatedDependency.Identifiers createRelatedDependencyIdentifiers() {
        return new RelatedDependency.Identifiers();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.Exception.StackTrace }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.Exception.StackTrace createExceptionStackTrace() {
        return new Exception.StackTrace();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.ScanInfo.DataSource }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.ScanInfo.DataSource createScanInfoDataSource() {
        return new com.rhizomind.ds.integrations.owasp.ScanInfo.DataSource();
    }

    /**
     * Create an instance of {@link com.rhizomind.ds.integrations.owasp.ScanInfo.AnalysisExceptions }
     * 
     */
    public com.rhizomind.ds.integrations.owasp.ScanInfo.AnalysisExceptions createScanInfoAnalysisExceptions() {
        return new ScanInfo.AnalysisExceptions();
    }

}
